name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - uses: actions/checkout@v4

      # Instala o Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # Cache do pip
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Instala MkDocs + Material
      - name: Install dependencies
        run: pip install mkdocs-material

      # Build MkDocs
      - name: Build MkDocs site
        run: mkdocs build

      # (Opcional) listar arquivos
      - name: List generated files
        run: ls -R site

      # Deploy para GitHub Pages
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mkdocs gh-deploy --force --remote-name origin
